### ISSUE TITLE
Garbled texture issue on ios

### ISSUE THREAD

**Issue by slasktotten** [vape/ScratchCard#1]
Hi!

Thanks for a really nice library! I've been trying to run it on mobile and have been running into some weird issues.

In editor, what I expect it to look like:
<img width="177" alt="Screenshot 2024-05-08 at 2 25 45" src="https://github.com/vape/ScratchCard/assets/16030559/a4e60e44-dcdb-4d53-b824-8cab290bc13a">

On ios device:
<img width="214" alt="Screenshot 2024-05-08 at 2 27 28" src="https://github.com/vape/ScratchCard/assets/16030559/5f5e0184-11a0-47dd-8596-4efb601c6917">

I dug through the code and this seems to be the issue:
```
            if (targetTexture == null)
            {
                targetTexture = RenderTexture.GetTemporary(width, height, -1, RenderTextureFormat.ARGB32);
                Image.texture = targetTexture;
                ClearTexture();
            }
```
Specifically the call to `RenderTexture.GetTemporary`. I tried a bunch of different render texture formats but that didnt fix the issue. Any thoughts/ideas?

**Comment by vape** [comment]
Hi @slasktotten!

I wasn't able to reproduce the issue on my side, but it looks like something either with brush material and/or its texture or render texture. If you could make a simple project where this problem persist I could look into it.

**Comment by slasktotten** [comment]
Hiya,

Awesome to have you check in :)

Here's a repro: [gdrive-link](https://drive.google.com/drive/folders/11rMZ_yhIs16VhiabQFcgf-4Js6UnB4do?usp=sharing)

However all I am doing is taking your sample scene and then try to replace the card texture with a different texture. 
<img width="1512" alt="Screenshot 2024-05-08 at 21 12 47" src="https://github.com/vape/ScratchCard/assets/16030559/ce5fd919-ca28-4946-b7eb-eba99dd7e8bd">

**Comment by slasktotten** [comment]
https://github.com/vape/ScratchCard/assets/16030559/41a45a37-d839-4b7f-99a9-d587f87805dc

this is from xcode!
here's another funny thing. the wonky looking areas that i remove, if i click restore they dont show up again

**Comment by vape** [comment]
@slasktotten got it fixed, should be working now

**Comment by slasktotten** [comment]
That works beautifully. Thank you so much! Tested in both simulator and on device
